version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      default_authentication_plugin: mysql_native_password
      MYSQL_USER: # Set MySQL USER
      MYSQL_PASSWORD: # Set MySQL USER_PASSWORD
      MYSQL_ROOT_PASSWORD:  # Set MySQL ROOT_PASSWORD
    volumes:
      - my-datavolume:/var/lib/mysql
    ports: 
      - 3306:3306

  website:
    image: easyvoc
    restart: always
    ports:
      - 5000:5000

volumes:
  my-datavolume: {}