FROM python:3.7.8-buster
COPY ./requirements.txt /var/www/requirements.txt
COPY ./.envvar /var/www/Server/.envar
COPY . /var/www/Server
RUN pip install -r /var/www/requirements.txt

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 5000